# Generated by Django 4.2.5 on 2023-09-13 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_rename_genre_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
