# Generated by Django 4.2.5 on 2023-09-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_movie_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='date_created',
        ),
    ]
