# Generated by Django 4.2.5 on 2023-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_rename_date_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dispo',
            field=models.BooleanField(default=False),
        ),
    ]
